name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@${{ github.event.inputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
